// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPfPG9Gymnx0jqZurauehM_ttySxaR2s',
    appId: '1:423321148950:web:f06694ca53a3c7dc26df37',
    messagingSenderId: '423321148950',
    projectId: 'cashcounter-b951f',
    authDomain: 'cashcounter-b951f.firebaseapp.com',
    storageBucket: 'cashcounter-b951f.appspot.com',
    measurementId: 'G-5CJYPC7B0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3KXYowdzjduPEFkFM3hlj7fWfVSEdh7U',
    appId: '1:423321148950:android:08d074d1748ca51026df37',
    messagingSenderId: '423321148950',
    projectId: 'cashcounter-b951f',
    storageBucket: 'cashcounter-b951f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr7Sykkq-zd50_QyGEDh1ejQ86HqFlEbI',
    appId: '1:423321148950:ios:86e508ffa5f6cd5326df37',
    messagingSenderId: '423321148950',
    projectId: 'cashcounter-b951f',
    storageBucket: 'cashcounter-b951f.appspot.com',
    androidClientId: '423321148950-ovcvt46ru8gor6c7r8psa0v89a7ib7nt.apps.googleusercontent.com',
    iosClientId: '423321148950-u21fpstiktptpdf3eifiinlta6h9h8a0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cashcounter',
  );
}
